# Generated by Django 6.0 on 2026-01-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GA4Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen_event', models.CharField(max_length=100)),
                ('fire_event', models.CharField(max_length=100)),
                ('url_contains', models.CharField(blank=True, max_length=255, null=True)),
                ('params_map', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listen_event', models.CharField(choices=[('click', 'Click'), ('dblclick', 'Double Click'), ('page_view', 'Page View'), ('scroll', 'Scroll'), ('form_submit', 'Form Submit')], max_length=50)),
                ('selector', models.CharField(blank=True, help_text='CSS selector del elemento', max_length=255, null=True)),
                ('url_contains', models.CharField(blank=True, max_length=255, null=True)),
                ('fire_event', models.CharField(max_length=100)),
                ('params_map', models.JSONField(blank=True, default=dict, null=True)),
                ('custom_js', models.TextField(blank=True, help_text='JS a ejecutar al cumplirse la regla', null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
